### ISSUE TITLE
across map fail when using condensed arguments

### ISSUE THREAD

**Issue by romain-dartigues** [keenerd/jshon#21]
Hi,

the manpage says:

> If you care about extremely short one liners, arguments can be condensed when it does not cause ambiguity.

But condensed arguments are not handled the same way.

Example:

```
$ echo '{"a":1,"b":[true,false,null,"none"],"c":{"d":4,"e":5}}' > sample.json
$ sample.json ./jshon -a -t
number
array
object

$ <sample.json jshon -at
number
bool
parse error: type not mappable
```

Regards.

**Comment by flying-sheep** [comment]
my take on golfing: `-at` should always mean `-a -t`

`-ename` should therefore mean `-e -n -a -m -e`, not `-e name`

**Comment by romain-dartigues** [comment]
Not really useful anymore, I'm closing my golf issue.
